assignments/urls.py
from django.urls import path

from assignments.views import AssignmentPageView, CreateAssignmentView, CreateTagView, EditAssignmentView

urlpatterns = [
    path('<int:pk>', AssignmentPageView.as_view(), name='assignment'),
    path('create_assignment', CreateAssignmentView.as_view(), name='create_assignment'),
    path('edit_assignment/<int:pk>', EditAssignmentView.as_view(), name='edit_assignment'),
    path('create_tag', CreateTagView.as_view(), name='create_tag')
]

easyprogramcheckin/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from easyprogramcheckin import settings

urlpatterns = [
    path('', include('courses.urls')),
    path('assignments/', include('assignments.urls')),
    path('registration/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('view_feedback', include('feedback.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import SignUpView, ProfileView
from users.forms import UserAuthenticationForm
from django.contrib.auth import views as viewsauth
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('signup/', SignUpView.as_view(extra_context={'title': 'Sign Up'}), name='signup'),
    path('login/', viewsauth.LoginView.as_view(template_name='registration/login.html',
                                               form_class=UserAuthenticationForm,
                                               extra_context={'title': 'Login'}),
         name='login'),
    path('profile/', ProfileView.as_view(extra_context={'title': 'Profile'}), name='profile'),
    path('logout/', viewsauth.LogoutView.as_view(), name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

assignments/models.py
import os
from django.db import models
from django.utils import timezone
from django.urls import reverse
from courses.models import Course
from django.core.files import File
from django.db.models.signals import post_save
from django.dispatch import receiver

from my_lib.files_wrapper import file_to_file, change_path_extension, get_file_name, check_if_file_is_valid


class Language(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return "#" + self.name


class Assignment(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(editable=False, blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    published = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=False)

    statement = models.FileField(upload_to='statements', blank=True, null=True)

    # Matipedia: I'm not sure how the period is stated in chars
    period = models.CharField(max_length=20, default="", blank=True, null=True)

    # source: https://docs.djangoproject.com/en/dev/ref/models/fields/#foreignkey
    original = models.ForeignKey('self', default=None, on_delete=models.PROTECT, blank=True, null=True)

    # The source with which the statement file was created (a .zip or another compression format)
    source = models.FileField(upload_to='source', blank=True, null=True)

    tests = models.FileField(upload_to='test_files', blank=True, null=True)

    allowed_languages = models.ManyToManyField(Language)

    def save(self, *args, **kwargs):
        """
        On save, update timestamps
        """
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()

        return models.Model.save(self, *args, **kwargs)

    def __str__(self):
        return self.course.code + ": " + self.title

    def get_absolute_url(self):
        return reverse('assignment', kwargs={'pk': self.pk})

    def get_source_name(self):
        return self.source.name.split("/")[-1]

    def get_statement_name(self):
        return self.statement.name.split("/")[-1]

    def get_tests_name(self):
        return self.tests.name.split("/")[-1]


@receiver(post_save, sender=Assignment)
def create_assignment(sender, instance, created, **kwargs):
    """
    Changes the file to a json on creation

    :param sender: The model class. (Assignment)
    :param instance: The actual instance being saved.
    :param created: Boolean; True if a new record was created.
    """

    if created and instance.tests:
        # Generates paths for the new json file
        test_url = instance.tests.url[1:]
        json_tests_url = change_path_extension(test_url, 'json')

        if not check_if_file_is_valid(test_url):
            instance.tests = None
            instance.save()
            os.remove(test_url)
            return

        # Passes the information from the original file to the json file
        file_to_file(test_url, json_tests_url)

        # Saves the new json file as the tests file in the instance
        f = open(json_tests_url)
        instance.tests.save(get_file_name(json_tests_url), File(f))
        f.close()

        # Deletes the old file
        os.remove(test_url)

assignments/views.py
import os
from django.utils import timezone
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import get_object_or_404
from assignments.models import Assignment, Tag
from assignments.forms import CreateAssignmentForm, EditAssignmentForm, CreateTagForm
from users.models import Account
from feedback.models import Feedback, PublicTestFeedback, SemiPrivateTestFeedback, PrivateTestFeedback
from feedback.scripts import SaveScriptProcess
from django.shortcuts import render
from django.core.files import File
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from my_lib.files_wrapper import check_if_file_is_valid, file_to_file, change_path_extension, get_file_name

from scriptserver.comunication.client import Client

ComunicationClient = Client()


class AssignmentPageView(TemplateView):
    template_name = "assignments/assignment_page.html"
    feedback_template_name = "feedback/immediate_feedback_page.html"
    feedback_error_template_name = "feedback/immediate_feedback_error_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        assignment = get_object_or_404(Assignment, id=self.kwargs['pk'])

        context['title'] = assignment.title

        context['teachers'] = Account.objects.filter(teaching_courses__id=assignment.course.id)
        context['assistants'] = Account.objects.filter(assistant_courses__id=assignment.course.id)

        context['isTeacher'] = context['teachers'].filter(id=self.request.user.id).exists()
        context['isAssistant'] = context['assistants'].filter(id=self.request.user.id).exists()

        if not assignment.published and not context['isTeacher'] and not context['isAssistant']:
            raise Http404

        context['input_examples'] = []
        context['output_examples'] = []

        context['has_tests'] = bool(assignment.tests)

        context['assignment'] = assignment

        context['tags'] = assignment.tags.all()

        assignment_course = assignment.course
        context['course'] = assignment_course
        context['course_url'] = assignment_course.get_absolute_url()
        context['langs'] = assignment.allowed_languages.all()
        return context

    def post(self, request, *args, **kwargs):
        # Get assignment and post data
        assignment = get_object_or_404(Assignment, id=self.kwargs['pk'])

        if not bool(assignment.tests):
            return self.handle_failed_single_response(request,
                                                      "The Assignment has no tests, talk to the course's teacher or assistants to fix this issue.",
                                                      **kwargs)

        data = request.POST.copy()

        # Get language and file from data
        lang = data.get('language')
        file = request.FILES.get('sample_code')

        # If the user didn´t uploaded a file it sends the user back to the same page
        if file == None:
            return render(request, self.template_name, self.get_context_data(**kwargs))

        # Save the file in the media folder
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

        # get the path from the media folder
        script_path = os.getcwd().replace("\\", "/") + "/media/" + filename
        test_path = assignment.tests.path.replace("\\", "/")

        if data["submission_type"] == "single":

            # Send and receive data for testing
            response = ComunicationClient.send_submission(script_path, test_path, lang)

            # Delete the source code file from the media folder
            os.remove('media/' + filename)
            if lang == 'C++11' or lang == 'Java 11':
                if lang == 'C++11':
                    out_name = os.path.splitext(filename)[0] + '.out'
                elif lang == 'Java 11':
                    out_name = os.path.splitext(filename)[0] + '.class'
                os.remove('media/' + out_name)

            if response[0] == "success":
                return self.handle_successful_single_response(request, assignment, response[1], **kwargs)
            else:
                return self.handle_failed_single_response(request, response[1], **kwargs)
        elif data["submission_type"] == "multiple":

            SaveScriptProcess(request.user.account, assignment, lang, ComunicationClient, script_path,
                              test_path).start()

            this_context = self.get_context_data(**kwargs)

            return render(request, self.template_name, this_context)
        else:

            # Delete the source code file from the media folder
            os.remove('media/' + filename)
            if lang == 'C++11' or lang == 'Java 11':
                if lang == 'C++11':
                    out_name = os.path.splitext(filename)[0] + '.out'
                elif lang == 'Java 11':
                    out_name = os.path.splitext(filename)[0] + '.class'
                os.remove('media/' + out_name)

            raise Exception("Unidentified submission")

    def handle_successful_single_response(self, request, assignment, tests_arr, **kwargs):
        # Save tests_arr as a feedback object and a group of simple_test_feedback objects
        if request.user.__str__() != "AnonymousUser":
            # Create the feedback object and save it in the database
            feedback_user = request.user.account
            feedback_assignment = assignment
            feedback_date = timezone.now()
            feedback = Feedback(user=feedback_user, assignment=feedback_assignment, date=feedback_date)
            feedback.save()

            # Save the tests as single_test_feedback object of diferent types depending on the test type
            for test in tests_arr:
                single_test_feedback = None

                # Case the test is public
                if test[4] == "public":
                    single_test_feedback = PublicTestFeedback(passed=bool(test[0]), input=test[1],
                                                              expected_output=test[2], actual_output=test[6],
                                                              comment=test[3], error=test[5],
                                                              feedback=feedback)
                # Case the test is semi private
                elif test[4] == "semi_private":
                    single_test_feedback = SemiPrivateTestFeedback(passed=bool(test[0]), input=test[1],
                                                                   expected_output=test[2], actual_output=test[6],
                                                                   comment=test[3],
                                                                   error=test[5],
                                                                   feedback=feedback)
                # Case the test is private
                else:
                    single_test_feedback = PrivateTestFeedback(passed=bool(test[0]), input=test[1],
                                                               expected_output=test[2], actual_output=test[6],
                                                               comment=test[3], error=test[5],
                                                               feedback=feedback)

                single_test_feedback.save()
        else:
            # Create the feedback object and save it in the database
            feedback_user = None
            feedback_assignment = assignment
            feedback_date = timezone.now()
            feedback = Feedback(user=feedback_user, assignment=feedback_assignment, date=feedback_date)
            feedback.save()

        this_context = self.get_context_data(**kwargs)

        passed_tests_dict_arr = []
        failed_tests_dict_arr = []

        i = 1
        for test in tests_arr:
            elem = dict()
            elem["num"] = i
            elem["input"] = test[1]
            elem["expected_output"] = test[2]
            elem["actual_output"] = test[6]
            elem["comment"] = test[3]
            elem["type"] = test[4]
            elem["error_code"] = test[5]
            if int(test[5]) == 0:
                elem["error"] = False
            else:
                elem["error"] = True
                if int(test[5]) == 1:
                    elem["error_detail"] = "Runtime or Compilation Error"
                elif int(test[5]) == 2:
                    elem["error_detail"] = "Timeout Error"
                else:
                    elem["error_detail"] = "Unknown Error"
            if not (elem["type"] == "private" and (not (this_context["isTeacher"] or this_context["isAssistant"]))):
                if bool(test[0]):
                    passed_tests_dict_arr.append(elem)

                else:
                    failed_tests_dict_arr.append(elem)

                i += 1

        if tests_arr == []:
            return render(request, self.template_name, self.get_context_data(**kwargs))
        else:
            this_context['passed_tests'] = passed_tests_dict_arr
            this_context['failed_tests'] = failed_tests_dict_arr
            return render(request, self.feedback_template_name, this_context)

    def handle_failed_single_response(self, request, error, **kwargs):
        this_context = self.get_context_data(**kwargs)
        this_context['error'] = error
        return render(request, self.feedback_error_template_name, this_context)


class CreateAssignmentView(CreateView):
    template_name = "assignments/assignment_form.html"
    model = Assignment
    form_class = CreateAssignmentForm

    obj = ""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        teaching_courses = self.request.user.account.teaching_courses.all()

assignments/templates/assignments/assignment_form.html
{% extends 'main_app/base.html' %}

{% load static %}

{% block specific_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6/css/select2.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'assignments/css/form.css' %}">
{% endblock specific_css %}

{% block content %}
    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form.media }}

    <div class="container">
        <div class="row my-5">
            <div class="col-1"></div>
            <div class="col-10">
                <h1>New Assignment</h1>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post" enctype="multipart/form-data" onsubmit="clearStorage()">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_title"><strong>Assignment Title <span
                                class="required_field">*</span></strong></label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="id_allowed_languages"><strong>Allowed Languages<span
                                class="required_field">*</span></strong></label>
                        {{ form.allowed_languages }}
                    </div>
                    <div class="form-group">
                        <label for="id_tags"><strong>Tags</strong></label>
                        {{ form.tags }}
                        <a href="" data-toggle="modal" data-target="#createTagModal">+ Create new tag</a>
                    </div>
                    <div class="form-group">
                        <label for="id_statement"><strong>Statement</strong></label>
                        {{ form.statement }}
                        <small id="statement_help" class="form-text text-muted">PDFs are accepted.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_source"><strong>Source</strong></label>
                        {{ form.source }}
                        <small id="source_help" class="form-text text-muted">The packed source code for the problem statement.</small>
                    </div>
                    <div class="form-group">
                        <label for="id_course"><strong>Course <span class="required_field">*</span></strong></label>
                        {{ form.course }}
                    </div>
                    <div class="form-group">
                        <label for="id_deadline"><strong>Deadline</strong></label>
                        {{ form.deadline }}
                    </div>
                    <div class="form-group">
                        <label for="id_period"><strong>Period</strong></label>
                        {{ form.period }}
                    </div>
                    <div class="form-group">
                        <label for="id_published"><strong>Is Published</strong></label>
                        {{ form.published }}
                    </div>
                    <div class="form-group">
                        <label for="id_tests"><strong>Test Cases</strong></label>
                        {{ form.tests }}
                        <small id="tests_help" class="form-text text-muted">All .csv, .yml, .yaml and .json files are
                            accepted. The format on this file can be found <a href="" data-toggle="modal"
                                                                              data-target=".bd-tutorial-modal-lg">here</a>.
                        </small>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                <div class="modal fade" id="createTagModal" tabindex="-1" role="dialog"
                     aria-labelledby="createTagModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="createTagModalLabel">New Tag</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <iframe id="tagForm" src="{% url "create_tag" %}" class="w-100 border-0"
                                        height="200px"></iframe>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal fade bd-tutorial-modal-lg" tabindex="-1" role="dialog"
                     aria-labelledby="myLargeModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="myLargeModalLabel">Accepted Test Files</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h4>Format of the File</h4>
                                <p>A file must contain an array of dictionaries with 4 parameters:</p>
                                <ul>
                                    <li>An Input that must be a string.</li>
                                    <li>An Output that must be a string.</li>
                                    <li>A Comment that must be a string.</li>
                                    <li>And a Test Type must be a string from the following: "public", "semi_private",
                                        "private". (If this field is not one of the previous strings the test will be
                                        taken as private).
                                    </li>
                                </ul>
                                <p>
                                    The Input and Output fields are very self explanatory, the comment is a string that
                                    explains the test and will show with the feedback of the test. Some examples are
                                    "Basic Tests", "Big Numbers Test", "Large Arrays", etc.

                                    The Test Type strinf indicates the type of feedback a test will have when a code
                                    sample
                                    is tested. The string "public" represent Public Tests, "semi_private" represents
                                    Semi-Private Tests and "private"
                                    are Private Tests:
                                </p>

                                <ul>
                                    <li>Public Tests: The feedback for this type of tests consists of a boolean
                                        indicating
                                        if it passed the test or not, the input, the expected output, the resulting
                                        output
                                        and the comment.
                                    </li>
                                    <li>Semi-Private Tests: The feedback for this type of tests consists of just the
                                        boolean
                                        and the comment.
                                    </li>
                                    <li>Semi-Private Tests: These tests aren't shown in the feedback.</li>
                                </ul>

                                <p>
                                    The specifications shown before are only for the student feedback, for the assistant
                                    and
                                    teacher feedback every test wiil be shown as if it were a public test.
                                </p>

                                <h4>File Examples</h4>
                                <h5>Json</h5>
                                <a href="{% static 'file_samples/example_test_file.json' %}"
                                   download="example_test_file.json"><i class="fa fa-file"></i> Download Example
                                    File</a>
                                <pre><code>[
    {
        "Input": "[1,2,3,4]",
        "Output": "1",
        "Comment": "A Comment",
        "Test Type": "public"
    },
    {
        "Input": "[5,6,7,8]",
        "Output": "0",
        "Comment": "Another Coment",
        "Test Type": "private"
    }
]

</code></pre>
                                <h5>Csv</h5>
                                <a href="{% static 'file_samples/example_test_file.csv' %}"
                                   download="example_test_file.csv"><i class="fa fa-file"></i> Download Example File</a>
                                <pre><code>Input,Output,Comment,Test Type
"[1,2,3,4]",1,A Comment,public
"[5,6,7,8]",0,Another Coment,private
</code></pre>
                                <h5>Yml and Yaml</h5>
                                <a href="{% static 'file_samples/example_test_file.yaml' %}"
                                   download="example_test_file.yaml"><i class="fa fa-file"></i> Download Example
                                    File</a>
                                <pre><code>---
- Input: "[1,2,3,4]"
  Output: '1'
  Comment: A Comment
  Test Type: public
- Input: "[5,6,7,8]"
  Output: '0'
  Comment: Another Coment
  Test Type: private
</code></pre>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>
{% endblock content %}

{% block specific_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6/js/select2.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#id_tags").select2();
            $("#id_allowed_languages").select2();

            // reload to get newly created tags
            $('#createTagModal').on('hidden.bs.modal', function () {
                window.location = window.location;
            })
        });

        let saveStorage = true;

        // save field values
        window.onbeforeunload = () => {
            if (saveStorage) {
                sessionStorage.setItem("title", $('#id_title').val());
                sessionStorage.setItem("tags", $('#id_tags').val());
                sessionStorage.setItem("course", $('#id_course').val());
                sessionStorage.setItem("deadline", $('#id_deadline').val());
                sessionStorage.setItem("period", $('#id_period').val());
                sessionStorage.setItem("published", $('#id_published').val());
                sessionStorage.setItem("allowed_languages", $('#id_allowed_languages').val());
            }
        };

        // restore field values
        window.onload = () => {
            let title = sessionStorage.getItem("title");
            if (title !== null) $('#id_title').val(title);
            let tags = sessionStorage.getItem("tags").split(",");
            if (tags !== null) $('#id_tags').val(tags).change();
            let course = sessionStorage.getItem("course");
            if (course !== null) $('#id_course').val(course);
            let deadline = sessionStorage.getItem("deadline");
            if (deadline !== null) $('#id_deadline').val(deadline);
            let period = sessionStorage.getItem("period");
            if (period !== null) $('#id_period').val(period);
            let published = sessionStorage.getItem("published");
            if (published !== null) $('#id_published').val(published);
            let allowed_languages = sessionStorage.getItem("allowed_languages").split(",");
            if (allowed_languages !== null) $('#id_allowed_languages').val(allowed_languages).change();
        };

        function clearStorage() {
            saveStorage = false;
            sessionStorage.clear();
        }
    </script>

    <script>
        $("#create_assignments_light").css("font-weight", "Bold");
    </script>

{% endblock specific_js %}