courses/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from courses.views import LandingPageView, SearchCoursesView, SearchAssignmentsView, CoursePageView, \
    CreateCoursePageView, courses_as_json, assignments_as_json, EditCoursePageView

urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),
    path('search_courses', SearchCoursesView.as_view(), name='search_courses'),
    path('search_assignments', SearchAssignmentsView.as_view(), name='search_assignments'),
    path('course/<int:pk>', CoursePageView.as_view(), name='course'),
    path('create_course', CreateCoursePageView.as_view(), name='create_course'),
    path('courses_as_json', courses_as_json, name='courses_as_json'),
    path('assignments_as_json', assignments_as_json, name='assignments_as_json'),
    path('edit_course/<int:pk>', EditCoursePageView.as_view(), name='edit_course')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

easyprogramcheckin/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from easyprogramcheckin import settings

urlpatterns = [
    path('', include('courses.urls')),
    path('assignments/', include('assignments.urls')),
    path('registration/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('view_feedback', include('feedback.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import SignUpView, ProfileView
from users.forms import UserAuthenticationForm
from django.contrib.auth import views as viewsauth
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('signup/', SignUpView.as_view(extra_context={'title': 'Sign Up'}), name='signup'),
    path('login/', viewsauth.LoginView.as_view(template_name='registration/login.html',
                                               form_class=UserAuthenticationForm,
                                               extra_context={'title': 'Login'}),
         name='login'),
    path('profile/', ProfileView.as_view(extra_context={'title': 'Profile'}), name='profile'),
    path('logout/', viewsauth.LogoutView.as_view(), name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User


class Course(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=25, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.code + " : " + self.name

    def get_absolute_url(self):
        return reverse('course', kwargs={'pk': self.pk})


@receiver(post_save, sender=Course)
def create_course(sender, instance, created, **kwargs):
    """
    Add the current user as a teacher for this course

    :param sender: The model class. (Course)
    :param instance: The actual instance being saved.
    :param created: Boolean; True if a new record was created.
    """

    if created:
        user = instance.created_by
        user.account.teaching_courses.add(instance)

courses/forms.py
from django import forms
from courses.models import Course
from users.models import User, Account


class CourseForm(forms.ModelForm):
    teachers = forms.ModelMultipleChoiceField(queryset=User.objects.none(), required=False)
    assistants = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)

    class Meta:
        model = Course
        fields = ('name', 'code', 'teachers', 'assistants')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['code'].widget.attrs['class'] = 'form-control'
        self.fields['teachers'].widget.attrs['class'] = 'form-control multiselect'
        self.fields['assistants'].widget.attrs['class'] = 'form-control multiselect'

        self.fields['name'].widget.attrs['placeholder'] = 'Example Name'
        self.fields['code'].widget.attrs['placeholder'] = 'ER3443'

        self.fields['teachers'].queryset = User.objects.exclude(id=self.user.id)

        self.fields['teachers'].widget.attrs['autocomplete'] = 'off'
        self.fields['assistants'].widget.attrs['autocomplete'] = 'off'

    def save_teachers(self, object_id):
        """
        Add teachers

        :param object_id: ID of the course object.
        """
        teachers = self.cleaned_data['teachers']
        for teacher in teachers:
            obj = Course.objects.get(pk=object_id)
            teacher.account.teaching_courses.add(obj)

    def save_assistants(self, object_id):
        """
        Add assistants

        :param object_id: ID of the course object.
        """
        assistants = self.cleaned_data['assistants']
        for assistant in assistants:
            obj = Course.objects.get(pk=object_id)
            assistant.account.assistant_courses.add(obj)


class CourseEdit(forms.ModelForm):
    teachers = forms.ModelMultipleChoiceField(queryset=User.objects.none(), required=False)
    assistants = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False)

    current_teachers = forms.ModelMultipleChoiceField(queryset=User.objects.none(), required=False, widget=forms.CheckboxSelectMultiple)
    current_assistants = forms.ModelMultipleChoiceField(queryset=User.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Course
        fields = ('name', 'code', 'teachers', 'assistants', 'current_teachers', 'current_assistants')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.course = kwargs.pop('course', None)
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['code'].widget.attrs['class'] = 'form-control'

        self.fields['teachers'].widget.attrs['class'] = 'form-control multiselect'

        self.fields['assistants'].widget.attrs['class'] = 'form-control multiselect'

        self.fields['name'].widget.attrs['value'] = self.course.name
        self.fields['code'].widget.attrs['value'] = self.course.code

        self.fields['current_teachers'].queryset = Account.objects.filter(teaching_courses__id=self.course.id)
        self.fields['current_assistants'].queryset = Account.objects.filter(assistant_courses__id=self.course.id)

        self.fields['teachers'].queryset = Account.objects.exclude(teaching_courses__id=self.course.id)
        self.fields['assistants'].queryset = Account.objects.exclude(assistant_courses__id=self.course.id)

        self.fields['teachers'].widget.attrs['autocomplete'] = 'off'
        self.fields['assistants'].widget.attrs['autocomplete'] = 'off'

    def save_teachers(self, object_id):
        """
        Add teachers

        :param object_id: ID of the course object.
        """
        obj = Course.objects.get(pk=object_id)
        adding_teachers = self.cleaned_data['teachers']
        for teacher in adding_teachers:
            teacher.teaching_courses.add(obj)

        deleting_teachers = self.cleaned_data['current_teachers']

        for teacher in deleting_teachers:
            teacher.teaching_courses.remove(obj)

    def save_assistants(self, object_id):
        """
        Add assistants

        :param object_id: ID of the course object.
        """
        obj = Course.objects.get(pk=object_id)

        adding_assistants = self.cleaned_data['assistants']

        for assistant in adding_assistants:
            assistant.assistant_courses.add(obj)

        deleting_assistants = self.cleaned_data['current_assistants']

        for assistant in deleting_assistants:
            assistant.assistant_courses.remove(obj)

    def save_course(self, object_id):
        Course.objects.filter(pk=object_id).update(name=self.cleaned_data['name'], code=self.cleaned_data['code'])

    def save_all(self, object_id):

        if len(self.fields['current_teachers'].queryset) == len(self.cleaned_data['current_teachers']):
            return

        self.save_teachers(object_id)
        self.save_assistants(object_id)
        self.save_course(object_id)

courses/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.db.models import Q
from django.core import serializers
import json
from courses.models import Course
from assignments.models import Assignment, Tag
from users.models import Account, User
from courses.forms import CourseForm, CourseEdit


class LandingPageView(TemplateView):
    template_name = "courses/landing_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = "Welcome"

        user = self.request.user

        if user.is_authenticated:

            # get courses as json
            teaching_courses = json.loads(serializers.serialize('json', user.account.teaching_courses.all()))
            assistant_courses = json.loads(serializers.serialize('json', user.account.assistant_courses.all()))

            # initialize courses
            courses = []

            # add courses where user is teacher
            for course in teaching_courses:
                pk = course['pk']
                code = course['fields']['code']
                name = course['fields']['name']
                courses.append({
                    'pk': pk,
                    'code': code,
                    'name': name,
                    'role': 'Teacher'
                })

            # add courses where user is assistant
            for course in assistant_courses:
                pk = course['pk']
                code = course['fields']['code']
                name = course['fields']['name']
                courses.append({
                    'pk': pk,
                    'code': code,
                    'name': name,
                    'role': 'Assistant'
                })

            context['courses'] = courses

        return context


class SearchCoursesView(TemplateView):
    template_name = "courses/search_courses.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Search Courses"
        courses = Course.objects.all()
        context['codes'] = courses.values_list('code', flat=True)
        context['names'] = courses.values_list('name', flat=True)
        return context


def courses_as_json(request):
    codes = request.GET.getlist('code[]')
    names = request.GET.getlist('name[]')

    q_objects = Q()  # Create an empty Q object to start with

    # 'or' the Q objects together
    if codes:
        for t in codes:
            q_objects |= Q(code=t)
    else:
        q_objects |= Q(code="")

    if names:
        for t in names:
            q_objects |= Q(name=t)
    else:
        q_objects |= Q(name="")

    courses = Course.objects.filter(q_objects)

    result_json = serializers.serialize('json', courses)
    return HttpResponse(result_json, content_type='application/json')


class SearchAssignmentsView(TemplateView):
    template_name = "courses/search_assignments.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Search Assignments"
        assignments = Assignment.objects.filter(published=True)
        tags = Tag.objects.all()
        context['titles'] = assignments.values_list('title', flat=True)
        context['tags'] = tags.values_list('name', flat=True)

        return context


def assignments_as_json(request):
    titles = request.GET.getlist('title[]')
    tags = request.GET.getlist('tag[]')
    q_objects = Q()  # Create an empty Q object to start with

    # 'or' the Q objects together
    if titles:
        for t in titles:
            q_objects |= Q(title=t)

    # 'or' the Q objects together
    if tags:
        tag_ids = []
        tag_objects = Tag.objects.filter(name__in=tags).all()
        for tag in tag_objects:
            tag_ids.append(tag.id)

        q_objects |= Q(tags__in=tag_ids)

    # get the assignments from the database
    assignments = Assignment.objects.filter(q_objects, published=True).distinct()

    # create a tag_id -> tag_name dictionary from the database
    tag_objects = Tag.objects.all()
    tag_dict = {}
    for object in tag_objects:
        tag_dict[object.id] = object.name

    # parses the assignments collection as a json string
    result_json_str = serializers.serialize('json', assignments)

    # transforms the string to a dictionary
    result_json = json.loads(result_json_str)

    # Changes the tags in the json from ids to names
    for model in result_json:
        model["fields"]["course"] = Course.objects.filter(id=model["fields"]["course"]).get().name
        model_tag_list = []
        for tag in model["fields"]["tags"]:
            model_tag_list.append(tag_dict[tag])

        model["fields"]["tags"] = model_tag_list

    # Passes the result dictionary to a json array
    result_json_str = json.dumps(result_json)

    return HttpResponse(result_json_str, content_type='application/json')


class CoursePageView(TemplateView):
    template_name = "courses/course_page.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        course = get_object_or_404(Course, id=self.kwargs['pk'])

        # Get teacher of this course
        teachers = Account.objects.filter(teaching_courses__id=course.id)

        # Get assistants of this course
        assistants = Account.objects.filter(assistant_courses__id=course.id)
        context['title'] = course.name
        context['course'] = course
        context['teachers'] = teachers
        context['assistants'] = assistants

        context['isTeacher'] = teachers.filter(id=self.request.user.id).exists()
        context['isAssistant'] = assistants.filter(id=self.request.user.id).exists()

        assignments = []
        if context['isTeacher'] or context['isAssistant']:
            assignments = Assignment.objects.filter(course=course)
        else:
            assignments = Assignment.objects.filter(course=course, published=True)

        periods = assignments.order_by('-deadline').values('period').all()

        assignment_groups = []
        period_dict = dict()
        for period in periods:
            period_val = period["period"]

            if not (period_val in period_dict):
                period_dict[period_val] = None
                element = dict()
                element["period"] = period_val
                element["assignments"] = assignments.filter(period=period_val)
                assignment_groups.append(element)

        context['assignment_groups'] = assignment_groups

        return context


class CreateCoursePageView(CreateView):
    template_name = "courses/course_form.html"
    model = Course
    form_class = CourseForm

    obj = ""

    def form_valid(self, form):
        # save user in created_by field
        self.obj = form.save(commit=False)
        self.obj.created_by = self.request.user

        # save object
        self.obj.save()

        # add teachers
        form.save_teachers(self.obj.id)

        # add assistants
        form.save_assistants(self.obj.id)

        return self.get_success_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Create Course"
        return context

    def get_form_kwargs(self, **kwargs):
        form_kwargs = super(CreateCoursePageView, self).get_form_kwargs()
        form_kwargs["user"] = self.request.user
        return form_kwargs

    def get_success_url(self):
        return HttpResponseRedirect(reverse('course', kwargs={'pk': self.obj.id}))


class EditCoursePageView(CreateView):
    template_name = "courses/course_edit.html"
    model = Course
    form_class = CourseEdit

    obj = ""

    def form_valid(self, form):
        self.obj = get_object_or_404(Course, id=self.kwargs['pk'])

        # update
        form.save_all(self.obj.id)

        return self.get_success_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = "Edit Course"

        course = get_object_or_404(Course, id=self.kwargs['pk'])

        # Get teacher of this course
        teachers = Account.objects.filter(teaching_courses__id=course.id)

        context['isTeacher'] = teachers.filter(id=self.request.user.id).exists()

        return context

    def get_form_kwargs(self, **kwargs):
        form_kwargs = super(EditCoursePageView, self).get_form_kwargs()
        form_kwargs["user"] = self.request.user
        form_kwargs['course'] = get_object_or_404(Course, id=self.kwargs['pk'])
        return form_kwargs

    def get_success_url(self):
        return HttpResponseRedirect(reverse('course', kwargs={'pk': self.obj.id}))

courses/templates/courses/course_edit.html
{% extends 'main_app/base.html' %}

{% load static %}

{% block specific_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet"/>
{% endblock specific_css %}

{% block content %}

    {% if not isTeacher %}

        Are you lost?


    {% else %}

        <div class="container">
            <div class="row my-5">
                <div class="col-1"></div>
                <div class="col-10">
                    <h1>Edit Course</h1>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_name">Course Name</label>
                            {{ form.name }}
                        </div>
                        <div class="form-group">
                            <label for="id_code">Course Code</label>
                            {{ form.code }}
                        </div>
                        <div class="form-group">
                            <label for="id_teachers">Add Teachers</label>
                            {{ form.teachers }}
                        </div>

                        <div class="form-group">
                            <label for="id_current_teachers">Delete Teachers</label>

                            {{ form.current_teachers }}
                        </div>

                        <div class="form-group">
                            <label for="id_assistants">Add Assistants</label>
                            {{ form.assistants }}
                        </div>

                        <div class="form-group">
                            <label for="id_current_assistants">Delete Assistants</label>
                            {% if form.current_assistants|length == 0 %}
                                <br>
                                This course does not have assistants yet
                            {% endif %}
                            {{ form.current_assistants }}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="col-1"></div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

{% block specific_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script type="text/javascript" src="{% static "courses/js/course_form.js" %}"></script>
{% endblock specific_js %}

courses/templates/courses/course_form.html
{% extends 'main_app/base.html' %}

{% load static %}

{% block specific_css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet"/>
{% endblock specific_css %}

{% block content %}

    <div class="container">
        <div class="row my-5">
            <div class="col-1"></div>
            <div class="col-10">
                <h1>New Course</h1>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Course Name <span class="required_field">*</span></label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_code">Course Code <span class="required_field">*</span></label>
                        {{ form.code }}
                    </div>
                    <div class="form-group">
                        <label for="id_teachers">Teachers</label>
                        {{ form.teachers }}
                        <small id="teacher_select_help" class="form-text text-muted">You are going to be a teacher by
                            default.
                        </small>
                        <table class="table mt-3" id="teachers_table">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ user.first_name }} {{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="form-group">
                        <label for="id_assistants">Assistants</label>
                        {{ form.assistants }}
                        <table class="table mt-3" id="assistants_table">
                            <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-1"></div>
        </div>
    </div>

{% endblock content %}

{% block specific_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script type="text/javascript" src="{% static "courses/js/course_form.js" %}"></script>

    <script>
        $("#create_course_light").css("font-weight", "Bold");
    </script>

{% endblock specific_js %}

courses/templates/courses/course_page.html
{% extends 'main_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-8 col-md-9">
                <div class="row">
                    <div class="col-8">
                        <h1>{{ course.code }}: {{ course.name }}</h1>
                    </div>
                    <div class="col-4 py-1">
                        {% if isTeacher %}
                            <a href="{% url 'edit_course' course.id %}" class="btn btn-warning">Edit</a>
                        {% endif %}

                        {% if isAssistant or isTeacher %}
                            <a href="{% url 'create_assignment' %}" class="btn btn-warning">Create Assignment</a>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% if assignment_groups|length > 0 %}
                            <h4>Assignments</h4>
                            {% for assignment_group in assignment_groups %}
                                {% if assignment_group.period %}
                                    <h5>{{ assignment_group.period }}</h5>
                                {% else %}
                                    <h5>No Period</h5>
                                {% endif %}
                                <ul>
                                    {% for assignment in assignment_group.assignments %}
                                        <li><a href="{% url 'assignment' assignment.pk %}">{{ assignment.title }}</a>
                                        {% if assignment.deadline %}
                                            Deadline: {{ assignment.deadline }}
                                        {% endif %}
                                        {% if not assignment.published %}
                                            (Not published)
                                        {% endif %}
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endfor %}
                        {% else %}
                            <h4>No assignments exist yet.</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-4 col-md-3">
                <div class="row my-3">
                    <div class="card w-100">
                        <div class="card-body">
                            <h5 class="card-title">Teachers</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for teacher in teachers %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ teacher.user }}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="row my-3">
                    <div class="card w-100">
                        <div class="card-body">
                            <h5 class="card-title">Assistants</h5>
                        </div>
                        {% if assistants|length > 0 %}
                            <ul class="list-group list-group-flush">
                                {% for assistant in assistants %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        {{ assistant.user }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    There are no assistants.
                                </li>
                            </ul>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

courses/templates/courses/landing_page.html
{% extends 'main_app/base.html' %}

{% load static %}

{% block specific_css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="{% static "courses/css/landing_page.css" %}">
{% endblock specific_css %}

{% block content %}
    <div class="container">
        <div class="row my-5">
            <div class="col">
                {% if user.is_authenticated %}
                    <div class="row justify-content-center my-5">
                        <h1>Welcome {{ user.first_name }} {{ user.last_name }}</h1>
                    </div>
                    <div class="row">
                        <h3>Your Courses</h3>
                    </div>
                    <div class="row mt-3">
                        <div class="col">
                            <table id="courses_table" class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Your Role</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for course in courses %}
                                    <tr>
                                        <td><a href="{% url 'course' course.pk %}">{{ course.code }}</a></td>
                                        <td><a href="{% url 'course' course.pk %}">{{ course.name }}</a></td>
                                        <td><a href="{% url 'course' course.pk %}">{{ course.role }}</a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% else %}
                    <div class="row justify-content-center my-5">
                        <h1>You don't have any courses</h1>
                    </div>
                    <div class="row justify-content-center mt-5">
                        <p><a href="{% url 'signup' %}">Sign Up</a> to start joining courses</p>
                    </div>
                    <div class="row justify-content-center mb-5">
                        <p>¿Already have an account? <a href="{% url 'login' %}">Login</a> to explore your courses</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

{% block specific_js %}
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="{% static "courses/js/landing_page.js" %}"></script>
{% endblock specific_js %}